Refactor reusable code from controller-bootstrap
aws-controllers-k8s/pkg pull request #2
Opened 2022-07-12 19:36 UTC by JamesJHPark

Issue: [aws-controllers-k8s/community/issues/1358](https://github.com/aws-controllers-k8s/community/issues/1358)

Description of changes:

- This PR is to refactor reusable code from controller-bootstrap in aws-controllers-k8s/pkg repository.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-12 20:49 UTC, vijtrip2 requested changes

2022-07-12 20:49 UTC, vijtrip2 commented on go.mod
> +require gopkg.in/src-d/go-git.v4 v4.13.1
```suggestion
require (
    gopkg.in/src-d/go-git.v4 v4.13.1
)
```

2022-07-12 20:49 UTC, vijtrip2 commented on util/common.go
> +func GetSDKVersion(awsSDKGoVersion string) string {
this function does nothing. remove it.

2022-07-12 20:49 UTC, vijtrip2 commented on util/git.go
> +package util
consider move this to new `git` package, instead of `util`

2022-07-12 20:49 UTC, vijtrip2 commented on util/common.go
> +package util
consider moving this to new `io` package instead of `util`

2022-07-12 21:16 UTC, vijtrip2 approved these changes

2022-07-12 21:20 UTC, RedbackThomson approved these changes
Good start. Thanks

2022-07-12 21:47 UTC, jaypipes commented
Hold off on merging this please. I have a few suggestions will put in review later.

2022-07-15 13:28 UTC, jaypipes requested changes
@JamesJHPark This isn't quite what I had in mind, actually... I was thinking that we would place this code into the `pkg/` directory of the *code-generator* repository and then import it from controller-bootstrap.

The `pkg/` source code repository is really meant for things that are common or generic across all of ACK, and in the future, even broader than ACK. I wanted to keep the dependencies for the `pkg/` source code repository as minimal as possible, and adding in dependencies on things like `go-git` I think should remain in the code-generator source code repository.

2022-07-22 18:29 UTC, JamesJHPark commented
Closing as per discussion. Please refer to [PR](https://github.com/aws-controllers-k8s/code-generator/pull/355).

2022-07-22 18:29 UTC, closed without merging